"""initial schema

Revision ID: e723dddd82db
Revises:
Create Date: 2026-03-26 10:37:45.864627

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e723dddd82db"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("link_domain", sa.String(), nullable=False),
        sa.Column("pool", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("link_pkey")),
    )
    op.create_table(
        "mirror",
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("pool", sa.Integer(), nullable=False),
        sa.Column("mirror", sa.String(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("mirror_pkey")),
    )
    op.create_table(
        "snapshot",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("pool", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_state",
            sa.Enum(
                "PENDING", "FAILED", "UPDATING", "FROZEN", "EXPIRED", name="snapshotstate"
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.Enum("GOOGLE", name="snapshotprovider"), nullable=False),
        sa.Column("snapshot_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("snapshot_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snapshot")
    op.drop_table("mirror")
    op.drop_table("link")
    # ### end Alembic commands ###
